[tools]
"aqua:awslabs/git-secrets" = "1.3.0"
uv = "0.12.23"

[tasks.grant-permissions]
description = "mise/ 内のスクリプトに実行権限を付与する"
quiet = true
shell = "bash -c"
run = [
  'find ./mise/ -type f \( -name "*.sh" -o -name "*.py" \) -exec chmod +x {} +',
]
